// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: rsocks.proto

package rsocks

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsocks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rsocks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rsocks_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_rsocks_proto protoreflect.FileDescriptor

var file_rsocks_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x72, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x3e, 0x0a, 0x08, 0x54, 0x65, 0x6c, 0x65, 0x43, 0x6f, 0x6e,
	0x6e, 0x12, 0x32, 0x0a, 0x08, 0x54, 0x65, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x0f, 0x2e,
	0x72, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f,
	0x2e, 0x72, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rsocks_proto_rawDescOnce sync.Once
	file_rsocks_proto_rawDescData = file_rsocks_proto_rawDesc
)

func file_rsocks_proto_rawDescGZIP() []byte {
	file_rsocks_proto_rawDescOnce.Do(func() {
		file_rsocks_proto_rawDescData = protoimpl.X.CompressGZIP(file_rsocks_proto_rawDescData)
	})
	return file_rsocks_proto_rawDescData
}

var file_rsocks_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rsocks_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: rsocks.Message
}
var file_rsocks_proto_depIdxs = []int32{
	0, // 0: rsocks.TeleConn.TeleConn:input_type -> rsocks.Message
	0, // 1: rsocks.TeleConn.TeleConn:output_type -> rsocks.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rsocks_proto_init() }
func file_rsocks_proto_init() {
	if File_rsocks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rsocks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rsocks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rsocks_proto_goTypes,
		DependencyIndexes: file_rsocks_proto_depIdxs,
		MessageInfos:      file_rsocks_proto_msgTypes,
	}.Build()
	File_rsocks_proto = out.File
	file_rsocks_proto_rawDesc = nil
	file_rsocks_proto_goTypes = nil
	file_rsocks_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TeleConnClient is the client API for TeleConn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeleConnClient interface {
	TeleConn(ctx context.Context, opts ...grpc.CallOption) (TeleConn_TeleConnClient, error)
}

type teleConnClient struct {
	cc grpc.ClientConnInterface
}

func NewTeleConnClient(cc grpc.ClientConnInterface) TeleConnClient {
	return &teleConnClient{cc}
}

func (c *teleConnClient) TeleConn(ctx context.Context, opts ...grpc.CallOption) (TeleConn_TeleConnClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TeleConn_serviceDesc.Streams[0], "/rsocks.TeleConn/TeleConn", opts...)
	if err != nil {
		return nil, err
	}
	x := &teleConnTeleConnClient{stream}
	return x, nil
}

type TeleConn_TeleConnClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type teleConnTeleConnClient struct {
	grpc.ClientStream
}

func (x *teleConnTeleConnClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *teleConnTeleConnClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TeleConnServer is the server API for TeleConn service.
type TeleConnServer interface {
	TeleConn(TeleConn_TeleConnServer) error
}

// UnimplementedTeleConnServer can be embedded to have forward compatible implementations.
type UnimplementedTeleConnServer struct {
}

func (*UnimplementedTeleConnServer) TeleConn(TeleConn_TeleConnServer) error {
	return status.Errorf(codes.Unimplemented, "method TeleConn not implemented")
}

func RegisterTeleConnServer(s *grpc.Server, srv TeleConnServer) {
	s.RegisterService(&_TeleConn_serviceDesc, srv)
}

func _TeleConn_TeleConn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeleConnServer).TeleConn(&teleConnTeleConnServer{stream})
}

type TeleConn_TeleConnServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type teleConnTeleConnServer struct {
	grpc.ServerStream
}

func (x *teleConnTeleConnServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *teleConnTeleConnServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TeleConn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rsocks.TeleConn",
	HandlerType: (*TeleConnServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TeleConn",
			Handler:       _TeleConn_TeleConn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rsocks.proto",
}
